### PR TITLE
Add Flow import examples.

### PR DESCRIPTION
**Pull request by marbex7**
The examples were lifted directly from Flow tests:

https://github.com/facebook/flow/blob/master/tests/import_type/import_type.js
https://github.com/facebook/flow/blob/master/tests/import_typeof/import_typeof.js

### CODE REVIEW

**Comment by romainl** [comment]
Thank you. I can't make any promise but I'll try to work on it this week-end.

That said, if you feel like toying around with BRE, feel free to try something :-).

**Comment by marbex7** [comment]
I'll have a go :-)

**Comment by marbex7** [comment]
https://github.com/romainl/ctags-patterns-for-javascript/pull/18

**Comment by dannyharding10** [comment]
Any movement on this? I just set up ctags today using this repo, and would love for it to work with flow as well! @romainl thanks for this repo by the way

**Pull request merged**
